=== yoyooli8/yoyooli8/sampleWeb/src/main/resources/config/common-sub-1.9.dtd
<!ELEMENT control (action+)>        	<!-- 整个应用的控制请求,control.xml的根标签; -->
<!ELEMENT action (input,output?)*>   	<!-- 请求动作标签,代表一个请求动作,各请求根据path属性进行区别;  -->

<!--
	path属性:Request请求路径,形如：/front/sh/login!index
	service属性：Request请求调用后台的WebService服务类,值为后台工程中spring-services.xml中Service对应的id值;
	method属性：服务类中的方法;
-->
<!ATTLIST action 						
	path CDATA #REQUIRED
	service CDATA #IMPLIED
	method  CDATA #IMPLIED				
>

<!ELEMENT input (parameter*)>		<!--请求参数标签,<action>中可包含多个<input>标签,各标签通过uid区别; -->
<!--
	uid属性：请求的唯一编号; 
	service属性：若填写,则重写父类action属性的service; 
	method属性：若填写,则重写父类action属性的method; 
	scope属性：默认以control.xml中的key从前台获取数据,若值为request,则以request中的key值封装InputObject; 
	desc属性：描述此次请求完成的功能; 
	sec属性：加密标识; 
	cache属性：是否从缓存读取，默认不缓存; 
-->
<!ATTLIST input 
	uid ID #REQUIRED				
	service  CDATA #IMPLIED 
	method CDATA #IMPLIED 
	scope (request|control) "control"
	desc CDATA #IMPLIED
	sec (true|false) "false"
	cache (true|false) "false"
>

<!ELEMENT parameter EMPTY>
<!--
	key属性：Request中对应的key;
	order属性：参数的顺序,按照验证需求添加;
	regex属性：按照验证需求添加
	         required|     必须输入
	         urlField|     URL验证
	         strRange|     字符串范围验证,填写格式为：strRange[0,1],strRange{0,1],strRange[0,1},strRange{0,1}
	         regex|        正则表达式验证
	         numRange|     数字范围验证,填写格式为：numRange[0,1],numRange{0,1],numRange[0,1},numRange{0,1}
	         numField|     输入数字
	         emailField|   email格式
	         dateRange|    日期范围，填写格式为：numRange[2010/01/01,2010/01/02],numRange{2010/01/01,2010/01/02],numRange[2010/01/01,2010/01/02},numRange{2010/01/01,2010/01/02}
	         dateField     日期格式 
	toKey属性：InputObject对象中params属性中的key值;
	scope属性：key属性对应值的取值范围
				1、若scope不配置,则默认为"request”,从前台请求中获取数据;
				2、若scope为"session",则根据key到session中获取对应值,并以toKey属性的值作为params的键值存储,key的配置规则为： session中key值[.属性][.属性];
				3、若scope为"constants”,则从com.ai.***.util.Constants.java中读取属性为key的值;
				4、若scope为"properties”,则从config/system.properties中读取数据;
				5、若scope为"file",则为前台上传文件
-->
<!ATTLIST parameter
	key CDATA #REQUIRED
	order CDATA #IMPLIED
	regex CDATA #IMPLIED
	toKey CDATA #IMPLIED
	scope (request|session|constants|properties|file) "request"
>

<!ELEMENT output (parameter*)>			<!--请求返回结果转换标签，output标签通过uid属性和input匹配; -->
<!--
	uid属性：请求的唯一编号;
	convertor属性：Json转换类 ; 
	method属性：转换json调用的方法;
-->
<!ATTLIST output 
	uid IDREF #REQUIRED
	convertor CDATA #IMPLIED
	method CDATA #IMPLIED
>

=== yoyooli8/yoyooli8/sampleWeb/target/classes/config/control-sub.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE control SYSTEM "common-sub-1.9.dtd">
<control>
    <action path="/common">
          <!-- regex="" 目前要可以取值如下:
               required:必须
               urlField:验证是否url格式的值
               strRange:字符串范围验证,strRange{n,m}|{n,m]|[n,m}|[n,m]
                        {，}为不包含,[,]为包含
               numRange:验证数字范围,配置格式如strRange
               dateRange:日期范围,如strRange
               dateField:日期验证
               numField:数字
               emailField:email验证
               regex:配置正则做校验,配置正则需要用{}包裹起来,如: regex{[a-z0-9]}
               
               注:当有多个验证时以半角;隔开，当使用regex验证时，且正则表达式里面有半角;时请不要使用多个验证.
          -->
       <input uid="loginUser" service="testBusiService" method="login" scope="control" >
           <parameter key="userName"     toKey="userName"   scope="request" regex="required;strRange{3,10}"/>
           <parameter key="userPwd"      toKey="userPwd"    scope="request" regex="required;strRange{6,10}"/>
       </input>
       <output uid="loginUser" convertor="com.ai.frame.dubbo.action.convert.CommonConvert" method="convert">
           <parameter key="returnCode"    toKey="rtnCode" />
     	   <parameter key="returnMessage" toKey="rtnMsg"  />
     	   <parameter key="userName"      toKey="uName"   />
     	   <parameter key="pwd"           toKey="uPwd"    />
     	   <parameter key="userId"        toKey="uId"     />
     	   <parameter key="mobile"        toKey="mobile"  />
     	   <parameter key="address"       toKey="address" />
       </output>
       <input uid="getLoginInfo" service="" method="" scope="control" >
           <parameter key="name"      toKey="name"    scope="request" />
       </input>
       <output uid="getLoginInfo" convertor="com.ai.frame.dubbo.action.convert.CommonConvert" method="convert">
           <parameter key="returnCode"    toKey="rtnCode" />
           <parameter key="returnMessage" toKey="rtnMsg"  />
           <parameter key="userName"      toKey="uName"   />
           <parameter key="pwd"           toKey="uPwd"    />
           <parameter key="userId"        toKey="uId"     />
           <parameter key="mobile"        toKey="mobile"  />
           <parameter key="address"       toKey="address" />
       </output>
       <input uid="uploadFile" service="userService" method="uploadFile" scope="control" >
           <parameter key="fname"     toKey="name"    scope="request" />
           <parameter key="data"      toKey="file"    scope="file" />
       </input>
       <output uid="uploadFile" convertor="com.ai.frame.dubbo.action.convert.CommonConvert" method="convert">
           <parameter key="returnCode"    toKey="rtnCode" />
           <parameter key="returnMessage" toKey="rtnMsg"  />
       </output>
    </action>
</control>
